# Generated by Django 5.0.6 on 2024-11-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebBuilder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentid', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=30, null=True)),
                ('course', models.CharField(max_length=30, null=True)),
                ('section', models.FloatField(null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='profile')),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
