# Generated by Django 5.0.6 on 2024-12-25 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebBuilder', '0005_userprofile_friends_friendrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='caption',
        ),
        migrations.RemoveField(
            model_name='post',
            name='angry_reactions',
        ),
        migrations.RemoveField(
            model_name='post',
            name='care_reactions',
        ),
        migrations.RemoveField(
            model_name='post',
            name='haha_reactions',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
