# Generated by Django 5.0.6 on 2024-12-26 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebBuilder', '0008_post_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
